server:
  port: 8762
eureka:
  instance:
    hostname: spring.cloud.eureka.node02.com # 服务端实例名
  client:
    register-with-eureka: false # 不向服务端注册服务，因为本身就是服务端
    fetch-registry: false # 服务端检索服务实例不检索自己，因为自己就是是服务端，主要是维护服务实例，不给消费者提供其他服务
    service-url:
      # defautlZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 默认 Eureka Server 的注册和查询服务 url
      defaultZone: http://spring.cloud.eureka.node01.com:8761/eureka/,http://spring.cloud.eureka.node03.com:8763/eureka/